on: [push]
name: RSec CI
jobs:
  build_and_test:
    name: RSec CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Testing all methods.
        uses: actions-rs/cargo@v1
        with:
          command: run
      - name: Testing all methods.
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --target-dir .
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: doc
